# This is a basic workflow to help you get started with Actions

name: Kube-hunter
on:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install kubectl
        uses: azure/setup-kubectl@v1  
      - name: Configure AWS credentials
        id: install 
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      - name: Update kube config
        run: aws eks update-kubeconfig --name clops-daaf-cluster --region us-east-1    
      # Runs a set of commands using the runners shell
      - name: Deploy kube-hunter to EKS
        run: |
          kubectl create ns kube-hunter
          kubectl config set-context --current --namespace=kube-hunter  
          kubectl apply -f https://raw.githubusercontent.com/aquasecurity/kube-hunter/master/job.yaml
          sleep 3
          kubectl --namespace=kube-hunter logs $(kubectl get pods --namespace=kube-hunter -o go-template --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}' | grep kube-hunter) > kubehunter.txt
      - name: Send email
        id: email
        uses: dawidd6/action-send-mail@v3.7.1
        with:
         server_address: smtp.gmail.com
         server_port: 465
         secure: true
         username: ${{secrets.MAIL_USERNAME}}
         password: ${{secrets.MAIL_PASSWORD}}
         subject: logs file related to kube-hunter
         to: ashi.s@cloudifyops.com
         from: github-action@gamil.com
         body: Build job of ${{github.repository}} completed successfully!
         attachments: 'kubehunter.txt' 
   

